# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
dist: trusty
latex: false

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntugis/ppa"
      - sourceline: "ppa:opencpu/jq"
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libv8-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libjq-dev

# before_install:
#   - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
#   - sudo add-apt-repository ppa:opencpu/jq --yes
#   - sudo apt-get --yes --force-yes update -qq
#   - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libv8-dev libprotobuf-dev protobuf-compiler libjq-dev

# before_install:
#   - sudo add-apt-repository -y ppa:ubuntugis/ppa --yes
#   - sudo apt-get --yes --force-yes update -qq
#   - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
